package toy.ktx.domain.dto.api;

import lombok.Data;
import toy.ktx.domain.mugunhwa.MugunghwaRoom;

@Data
public class MugunghwaRoomWithSeatDto {
    private Long roomId;

    private String roomName;

    private Boolean m1;
    private Boolean m2;
    private Boolean m3;
    private Boolean m4;
    private Boolean m5;
    private Boolean m6;
    private Boolean m7;
    private Boolean m8;
    private Boolean m9;
    private Boolean m10;
    private Boolean m11;
    private Boolean m12;
    private Boolean m13;
    private Boolean m14;
    private Boolean m15;
    private Boolean m16;
    private Boolean m17;
    private Boolean m18;

    private Boolean m19;
    private Boolean m20;
    private Boolean m21;
    private Boolean m22;
    private Boolean m23;
    private Boolean m24;
    private Boolean m25;
    private Boolean m26;
    private Boolean m27;
    private Boolean m28;
    private Boolean m29;
    private Boolean m30;
    private Boolean m31;
    private Boolean m32;
    private Boolean m33;
    private Boolean m34;
    private Boolean m35;
    private Boolean m36;

    private Boolean m37;
    private Boolean m38;
    private Boolean m39;
    private Boolean m40;
    private Boolean m41;
    private Boolean m42;
    private Boolean m43;
    private Boolean m44;
    private Boolean m45;
    private Boolean m46;
    private Boolean m47;
    private Boolean m48;
    private Boolean m49;
    private Boolean m50;
    private Boolean m51;
    private Boolean m52;
    private Boolean m53;
    private Boolean m54;
    private Boolean m55;

    private Boolean m56;
    private Boolean m57;
    private Boolean m58;
    private Boolean m59;
    private Boolean m60;
    private Boolean m61;
    private Boolean m62;
    private Boolean m63;
    private Boolean m64;
    private Boolean m65;
    private Boolean m66;
    private Boolean m67;
    private Boolean m68;
    private Boolean m69;
    private Boolean m70;
    private Boolean m71;
    private Boolean m72;

    public MugunghwaRoomWithSeatDto(MugunghwaRoom mugunghwaRoom) {
        this.roomId = mugunghwaRoom.getId();
        this.roomName = mugunghwaRoom.getRoomName();
        this.m1 = mugunghwaRoom.getMugunghwaSeat().getM1();
        this.m2 = mugunghwaRoom.getMugunghwaSeat().getM2();
        this.m3 = mugunghwaRoom.getMugunghwaSeat().getM3();
        this.m4 = mugunghwaRoom.getMugunghwaSeat().getM4();
        this.m5 = mugunghwaRoom.getMugunghwaSeat().getM5();
        this.m6 = mugunghwaRoom.getMugunghwaSeat().getM6();
        this.m7 = mugunghwaRoom.getMugunghwaSeat().getM7();
        this.m8 = mugunghwaRoom.getMugunghwaSeat().getM8();
        this.m9 = mugunghwaRoom.getMugunghwaSeat().getM9();
        this.m10 = mugunghwaRoom.getMugunghwaSeat().getM10();
        this.m11 = mugunghwaRoom.getMugunghwaSeat().getM11();
        this.m12 = mugunghwaRoom.getMugunghwaSeat().getM12();
        this.m13 = mugunghwaRoom.getMugunghwaSeat().getM13();
        this.m14 = mugunghwaRoom.getMugunghwaSeat().getM14();
        this.m15 = mugunghwaRoom.getMugunghwaSeat().getM15();
        this.m16 = mugunghwaRoom.getMugunghwaSeat().getM16();
        this.m17 = mugunghwaRoom.getMugunghwaSeat().getM17();
        this.m18 = mugunghwaRoom.getMugunghwaSeat().getM18();
        this.m19 = mugunghwaRoom.getMugunghwaSeat().getM19();
        this.m20 = mugunghwaRoom.getMugunghwaSeat().getM20();
        this.m21 = mugunghwaRoom.getMugunghwaSeat().getM21();
        this.m22 = mugunghwaRoom.getMugunghwaSeat().getM22();
        this.m23 = mugunghwaRoom.getMugunghwaSeat().getM23();
        this.m24 = mugunghwaRoom.getMugunghwaSeat().getM24();
        this.m25 = mugunghwaRoom.getMugunghwaSeat().getM25();
        this.m26 = mugunghwaRoom.getMugunghwaSeat().getM26();
        this.m27 = mugunghwaRoom.getMugunghwaSeat().getM27();
        this.m28 = mugunghwaRoom.getMugunghwaSeat().getM28();
        this.m29 = mugunghwaRoom.getMugunghwaSeat().getM29();
        this.m30 = mugunghwaRoom.getMugunghwaSeat().getM30();
        this.m31 = mugunghwaRoom.getMugunghwaSeat().getM31();
        this.m32 = mugunghwaRoom.getMugunghwaSeat().getM32();
        this.m33 = mugunghwaRoom.getMugunghwaSeat().getM33();
        this.m34 = mugunghwaRoom.getMugunghwaSeat().getM34();
        this.m35 = mugunghwaRoom.getMugunghwaSeat().getM35();
        this.m36 = mugunghwaRoom.getMugunghwaSeat().getM36();
        this.m37 = mugunghwaRoom.getMugunghwaSeat().getM37();
        this.m38 = mugunghwaRoom.getMugunghwaSeat().getM38();
        this.m39 = mugunghwaRoom.getMugunghwaSeat().getM39();
        this.m40 = mugunghwaRoom.getMugunghwaSeat().getM40();
        this.m41 = mugunghwaRoom.getMugunghwaSeat().getM41();
        this.m42 = mugunghwaRoom.getMugunghwaSeat().getM42();
        this.m43 = mugunghwaRoom.getMugunghwaSeat().getM43();
        this.m44 = mugunghwaRoom.getMugunghwaSeat().getM44();
        this.m45 = mugunghwaRoom.getMugunghwaSeat().getM45();
        this.m46 = mugunghwaRoom.getMugunghwaSeat().getM46();
        this.m47 = mugunghwaRoom.getMugunghwaSeat().getM47();
        this.m48 = mugunghwaRoom.getMugunghwaSeat().getM48();
        this.m49 = mugunghwaRoom.getMugunghwaSeat().getM49();
        this.m50 = mugunghwaRoom.getMugunghwaSeat().getM50();
        this.m51 = mugunghwaRoom.getMugunghwaSeat().getM51();
        this.m52 = mugunghwaRoom.getMugunghwaSeat().getM52();
        this.m53 = mugunghwaRoom.getMugunghwaSeat().getM53();
        this.m54 = mugunghwaRoom.getMugunghwaSeat().getM54();
        this.m55 = mugunghwaRoom.getMugunghwaSeat().getM55();
        this.m56 = mugunghwaRoom.getMugunghwaSeat().getM56();
        this.m57 = mugunghwaRoom.getMugunghwaSeat().getM57();
        this.m58 = mugunghwaRoom.getMugunghwaSeat().getM58();
        this.m59 = mugunghwaRoom.getMugunghwaSeat().getM59();
        this.m60 = mugunghwaRoom.getMugunghwaSeat().getM60();
        this.m61 = mugunghwaRoom.getMugunghwaSeat().getM61();
        this.m62 = mugunghwaRoom.getMugunghwaSeat().getM62();
        this.m63 = mugunghwaRoom.getMugunghwaSeat().getM63();
        this.m64 = mugunghwaRoom.getMugunghwaSeat().getM64();
        this.m65 = mugunghwaRoom.getMugunghwaSeat().getM65();
        this.m66 = mugunghwaRoom.getMugunghwaSeat().getM66();
        this.m67 = mugunghwaRoom.getMugunghwaSeat().getM67();
        this.m68 = mugunghwaRoom.getMugunghwaSeat().getM68();
        this.m69 = mugunghwaRoom.getMugunghwaSeat().getM69();
        this.m70 = mugunghwaRoom.getMugunghwaSeat().getM70();
        this.m71 = mugunghwaRoom.getMugunghwaSeat().getM71();
        this.m72 = mugunghwaRoom.getMugunghwaSeat().getM72();
    }
}
